-- Adds automatic translation storage for dynamic game content.
-- Run this migration against your Supabase Postgres instance.

create table if not exists public.game_translations (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.games(id) on delete cascade,
  locale text not null,
  title text,
  description text,
  long_description text[],
  source_hash text not null,
  status text not null default 'machine' check (status in ('machine', 'reviewed', 'human')),
  translated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (game_id, locale, source_hash)
);
create index if not exists idx_game_translations_game_locale
  on public.game_translations (game_id, locale);
create index if not exists idx_game_translations_source_hash
  on public.game_translations (source_hash);
alter table public.game_translations enable row level security;
create policy "read game translations"
on public.game_translations
for select
to anon, authenticated
using (true);