import type { Metadata } from "next";
import { ColorSchemeScript, MantineProvider, createTheme, mantineHtmlProps } from '@mantine/core';
import '@mantine/core/styles.css';
import '../styles/globals.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  fontFamily: 'Geist, sans-serif',
  fontFamilyMonospace: 'Geist Mono, monospace',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className='antialiased'>
        <MantineProvider theme={theme}>{children}</MantineProvider>
      </body>
    </html>
  );
}
